---
role:
  pkg:
    # Install 'dig'
    - name: dnsutils
      os: ["debian"]
    # Install 'lwp-request'
    - name: libwww-perl
      os: ["debian"]
  dir:
    - bin
  link:
    - .* # aliases, curlrc, exports, hushlogin, inputrc
    - "bin/*:bin"
  line:
    ".path": "~/bin"
  block:
    ".profile": |
      # Global environment variables
      if [ -f ~/.exports ]; then
        . ~/.exports
      fi

      # Append to PATH
      # PATH="$PATH:$HOME/bin"
      if [ -f ~/.path ]; then
        source "$HOME"/bin/load_path
        load_path ~/.path
      fi

      #shopt -s expand_aliases
      if [ -f ~/.aliases ]; then
        . ~/.aliases
      fi
