---
role:
  pkg:
    # Install 'dig'
    - name: dnsutils
      os: ["debian"]
    # Install 'lwp-request'
    - name: libwww-perl
      os: ["debian"]

    - name: shunit2
      os: ["darwin"]
  dir:
    - bin
  link:
    - .* # aliases, curlrc, exports, hushlogin, inputrc
    - "bin/*:bin"
  line:
    ".path": "~/bin"
    ".profile": ". ~/.sh_profile"
