---
role:
  pkg:
    # Install 'dig'
    - name: dnsutils
      os: ["debian"]
    # Install 'lwp-request'
    - name: libwww-perl
      os: ["debian"]
  dir:
    - bin
  link:
    - .* # aliases, curlrc, exports, hushlogin, inputrc
    - "bin/*:bin"
